---
abstract: 'Minimal MQTT version 3 interface'
author:
  - 'Juerd Waalboer <juerd@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-MQTT-Simple
no_index:
  directory:
    - t
    - inc
requires: {}
version: '1.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
